app_id: 80B901C8-D6FE-494E-8AF7-A2BD440E8644
publisher: PhuCoderagga
publisher_url: https://github.com/PhuCoderagga/workflow
display_name: Spotube
create_desktop_icon: true
install_dir_name: Spotube
locales:
  - en
